version: '3'
services:
  ntfy:
    image: binwiederhier/ntfy
    restart: unless-stopped
    ports:
      - "8447:80"
    volumes:
      - /var/cache/ntfy:/var/cache/ntfy
      - /home/ahmed/apps/ntfy:/etc/ntfy
    command: ["serve", "--cache-file", "/var/cache/ntfy/cache.db"]
    tty: true
