version: '3'
services:
  firefox:
    image: jlesage/firefox
    ports:
      - "5800:5800"
    volumes:
      - "~/Downloads:/Downloads"
      - "~/Documents:/Documents"
      - "/docker/appdata/firefox:/config:rw"
    environment:
      - VNC_PASSWORD=${VNC_PASSWORD}
