version: '3'
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /home/ahmed/apps/homarr/configs:/app/data/configs
      - /home/ahmed/apps/homarr/icons:/app/public/icons
      - /home/ahmed/apps/homarr/data:/data
      - /home/ahmed/apps/homarr/img:/app/public/img
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '82:7575'
    environment:
      - TZ=Africa/Cairo
      - PASSWORD=${HOMARR_PASSWORD}
  dash:
    image: mauricenino/dashdot:latest
    container_name: homarr-dash
    ports:
      - '3001:3001'
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/mnt/host:ro
