version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_SCHEDULE: 0 0 20 * * *
      TZ: Africa/Cairo
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATION_URL: ntfy://ntfy.server.ahmedsaed.me/watchtower?title=WatchtowerUpdates
